### ISSUE TITLE
Image uploads / AWS work

### ISSUE THREAD

**Issue by ascott** [participedia/api#811]
- [x] - create staging bucket 
- [x] - optimize existing images
- [x] - create flow to optimize new images as they are added to entries
- [x] - for optimization let's create 2 sizes: thumbnails and full size. let's make the thumbnails  a max width of 600px and the fullsize a max width of 1600px.
- [x] Use the thumbnail image on the item list view.
- [ ] Use lambda to resize images instead of the code.
- [ ] set content encoding to either deflate or gzip so they are compatible with FB sharing

**Comment by paninee** [comment]
@ascott  I make the thumbnail a max width or height of 600px, instead of 600x300. Since the image uploaded could be either portrait and landscape, and we don't want to mess up the image ratio or cut the user's raw uploaded data. If we want to display it on a 600x300 div, I think we should just make that display in the frontend.

**Comment by ascott** [comment]
@paninee yes, i agree, let's make the thumbnail a max width of 600px. i'll update the todo.

**Comment by paninee** [comment]
Devs, please add `AWS_S3_BUCKET` /  `participedia.stage` to your dev env variables.

**Comment by paninee** [comment]
We would release this feature in 2 phases.

# Phase 1
This phase would deal with the new image uploads.
- New images will be in the new bucket with the optimization for thumbnail and full size.
- The thumbnail won't be displayed anywhere. The optimized full image would be displayed as it normally would.
- The image URL data in postgres would not be changed.

### Deployment process
- Add new `AWS_S3_BUCKET` env var on Heroku stage and prod respectively.
- Update the existing `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_UPLOADS_URL` env vars on Heroku stage to the new S3 account/bucket.
- Deploy https://github.com/participedia/api/commit/6caa5589e510b3124b026e51b4caf81709f7f3cc to stage
- Test on stage
- Put production on maintenance mode. This time probably less than an hour.
- Update the existing `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_UPLOADS_URL` env vars on Heroku prod to the new S3 account/bucket.
- Deploy the same change to production
- Turn off maintenance mode.
- Test on production

# Phase 2
This phase would deal with the existing assets.
- Existing images will be copied over to new bucket with the optimization for thumbnail and full size.
- The thumbnail would be displayed in the list view (case, method, organization). The optimized full image would be displayed as it normally would.
- The image URL data in postgres would be updated to reflect the new bucket URL and thumbnail data.

### Deployment process
- I would run the script `copy-optimize-images-to-new-bucket.js` locally to copy and optimize all assets to stage bucket. (~4300 files)
- Run `{{TBD}}` script to update the URL data in staging postgres.
- Test on stage. Check to make sure that existing images display correctly.
- Put production on maintenance mode. This time would be 2-4h.
- I would run the same 2 scripts on prod data.
- Turn off maintenance mode.
- Test on production

@ascott I would still prefer to do both phase one right after another though.

**Comment by paninee** [comment]
Next step is to use the thumbnail images.

- [ ] Use the thumbnail image on the item list view.

**Comment by ascott** [comment]
@paninee there is an issue with the way our images are currently encoded that prevents them from being shared on FB. Currently our images are encoded as base64, but FB requires them to be encoded as either deflate or gzip. 

here is the warning from FB:
<img width="1007" alt="Screen Shot 2020-02-07 at 12 50 51 PM" src="https://user-images.githubusercontent.com/130878/74065609-260ee600-49aa-11ea-9215-9fe6f71feb15.png">

and we can see here that our encoding is base64:
<img width="613" alt="Screen Shot 2020-02-07 at 1 01 18 PM" src="https://user-images.githubusercontent.com/130878/74065635-38891f80-49aa-11ea-8b08-38ca5e51cf27.png">

when you get to the task of using lamda to resize and optimize our images, can you also set the content-encoding to either deflate or gzip?

**Comment by ascott** [comment]
**Current functionality on staging**
        - file gets uploaded to root of bucket, this triggers Lambda function, if the file is an image,  create a thumbnail sized image and save it to a folder called `thumbnails`
        - article cards are now displayed using the thumbnail image 
        - large/fullsize images are not yet being optimized or resized

**Next steps to bring wrap this up**

- [ ]     add AWS Lambda function code to github so it’s in version control
- [ ]     add documentation to wiki about how to deploy AWS Lambda code and how to test it locally
- [ ]     copy all raw images to a folder called `raw` in s3 bucket root
- [ ]     lambda trigger update: when new image is saved to raw folder, optimize/resize and save thumbnail image to thumbnail folder, and optimize/resize large/fullsize image to root
- [ ]     set content-encoding to thumbnail and large/fullsize image to gzip to support FB sharing

**Comment by paninee** [comment]
@ascott 

> add documentation to wiki about how to deploy AWS Lambda code and how to test it locally
I've never tested the lambda function itself locally. I just test the script by running `node ____.js` as we would normally run. Do I need to figure out how to test calling the lambda function locally ?

> set content-encoding to thumbnail and large/fullsize image to gzip to support FB sharing
Do we want to update all the content-encoding for existing images as well?

**Comment by paninee** [comment]
Tests:

raw - https://s3.amazonaws.com/participedia.stage/raw/large_test.jpeg
large - https://s3.amazonaws.com/participedia.stage/large_test.jpeg
thumbnail - https://s3.amazonaws.com/participedia.stage/thumbnail/large_test.jpeg

**Comment by paninee** [comment]
GZip tests:

raw - https://s3.amazonaws.com/participedia.stage/raw/11850.jpg
large - https://s3.amazonaws.com/participedia.stage/11850.jpg
thumbnail - https://s3.amazonaws.com/participedia.stage/thumbnail/11850.jpg

**Comment by paninee** [comment]
Completed upload tests

raw - https://s3.amazonaws.com/participedia.stage/raw/bf3c5f98-3637-4827-b0aa-85ac23872305
large - https://s3.amazonaws.com/participedia.stage/bf3c5f98-3637-4827-b0aa-85ac23872305
thumbnail - https://s3.amazonaws.com/participedia.stage/thumbnail/bf3c5f98-3637-4827-b0aa-85ac23872305

**Comment by paninee** [comment]
All existing images in stage bucket are now in GZip format.

**Comment by paninee** [comment]
Production deployment plan

1. Run `gzip-assets.js` to convert existing assets into GZip
2. Copy over raw images to `raw/`
3. Link Lambda function to prod S3 `/raw` directory
4. Push and deploy code to production

**Comment by ascott** [comment]
@paninee thanks for all these updates! 🙌 
i noticed the thumbnail for completed uplaod tests is not returning the correctly...
thumbnail - https://s3.amazonaws.com/participedia.stage/thumbnail/bf3c5f98-3637-4827-b0aa-85ac23872305

<img width="1680" alt="Screen Shot 2020-02-15 at 12 28 20 PM" src="https://user-images.githubusercontent.com/130878/74594768-b7a3d680-4fee-11ea-8188-21d69a0f1ade.png">

**Comment by paninee** [comment]
@ascott when did you upload this image? I haven't deployed the code to stage yet.

**Comment by paninee** [comment]
New wiki page here https://github.com/participedia/api/wiki/AWS-Lambda.

**Comment by ascott** [comment]
@paninee i didn't upload this image, this is from your links posted in this comment: https://github.com/participedia/api/issues/811#issuecomment-586556499

**Comment by paninee** [comment]
hmmm, weird. I just look at it yesterday. I will check.

**Comment by paninee** [comment]
Other thumbnails work. I think I deleted this accidentally while testing the uploads locally. I will update the comment with a new test completed on stage in a bit.

**Comment by paninee** [comment]
@ascott AWS Lambda image resizing feature is ready for testing on stage

**Comment by ascott** [comment]
@paninee thanks! i will take a look at this today 👍

**Comment by ascott** [comment]
@paninee  this is looking really good! i noticed that thumbnails are not working correctly for gif images. i think once that is fixed we should be good to go!

**Comment by paninee** [comment]
Deployed and tested with a few images on prod.
